name: stable
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 */15 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Gh login
      run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token; gh auth setup-git; gh auth status
    - name: Run
      run: ./generate "$(curl -sL kernel.org|grep -A1 'stable:'|sed -n 's/.*strong>\(.*\)<\/strong.*/\1/p'|sed 's/<span.*\|\s//g')"
